### ISSUE TITLE
Problems with parallelization within a batch using `const` token

### ISSUE THREAD

**Issue by Sean-Reilly** [brendenpetersen/deep-symbolic-optimization#14] opened 2021-08-18 23:48 UTC
Hello Again,

So I've been trying to get the parallelization working for this, and when I set `n_cores_batch = 2` in the `config.json` file it keeps giving me the error below.  I'm not sure what is causing this issue, and it persists with any other value for `n_cores_batch` other than 1.   Do you have any insight into why this might be?

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/software/anaconda/3/envs/dso-sw/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/software/anaconda/3/envs/dso-sw/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/nas0/tluchko/sandbox/deep-symbolic-optimization/dso/dso/train.py", line 28, in work
    optimized_constants = p.optimize()
  File "/nas0/tluchko/sandbox/deep-symbolic-optimization/dso/dso/program.py", line 393, in optimize
    optimized_constants = Program.const_optimizer(f, x0)
TypeError: 'NoneType' object is not callable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rundso.py", line 9, in <module>
    model.train()
  File "/nas0/tluchko/sandbox/deep-symbolic-optimization/dso/dso/core.py", line 90, in train
    **self.config_training))
  File "/nas0/tluchko/sandbox/deep-symbolic-optimization/dso/dso/train.py", line 278, in learn
    results = pool.map(work, programs_to_optimize)
  File "/home/software/anaconda/3/envs/dso-sw/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/software/anaconda/3/envs/dso-sw/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: 'NoneType' object is not callable

```

**Comment by brendenpetersen** [comment] 2021-08-20 02:56
Hi @Sean-Reilly , can you send me the full config you're using and the method to run (CLI vs Python interface)?

**Comment by Sean-Reilly** [comment] 2021-08-20 03:12
I tried in both CLI and Python interface and got the same error as above.  Below is the full `config.json` of a failed run. 

```
{
   "experiment": {
      "logdir": "./log",
      "seed": 0,
      "timestamp": "2021-08-18-142149",
      "task_name": "~_nas_rism-symbolic-regression_dso_data_hs_dens_0.1",
      "save_path": "./log/~_nas_rism-symbolic-regression_dso_data_hs_dens_0.1_2021-08-18-142149"
   },
   "task": {
      "task_type": "regression",
      "dataset": "~/nas/rism-symbolic-regression/dso/data/hs_dens_0.1.csv",
      "function_set": [
         "add",
         "mul",
         "div",
         "sub",
         "const"
      ],
      "metric": "inv_nrmse",
      "metric_params": [
         1.0
      ],
      "extra_metric_test": null,
      "extra_metric_test_params": [],
      "threshold": 1e-20,
      "protected": false,
      "reward_noise": 0.0,
      "reward_noise_type": "r",
      "normalize_variance": false
   },
   "training": {
      "n_epochs": null,
      "n_samples": 100000,
      "batch_size": 100,
      "epsilon": 0.05,
      "baseline": "R_e",
      "alpha": 0.5,
      "b_jumpstart": false,
      "n_cores_batch": 4,
      "complexity": "token",
      "const_optimizer": "scipy",
      "const_params": {},
      "verbose": true,
      "debug": 0,
      "early_stopping": true,
      "hof": 5,
      "use_memory": false,
      "memory_capacity": 1000.0,
      "warm_start": null,
      "memory_threshold": null,
      "save_all_epoch": false,
      "save_summary": false,
      "save_positional_entropy": false,
      "save_pareto_front": true,
      "save_cache": false,
      "save_cache_r_min": 0.9,
      "save_freq": 1,
      "runs": 100
   },
   "controller": {
     "max_length": 30,
      "cell": "lstm",
      "num_layers": 1,
      "num_units": 32,
      "initializer": "zeros",
      "embedding": false,
      "embedding_size": 8,
      "learning_rate": 0.0005,
      "optimizer": "adam",
      "observe_action": false,
      "observe_parent": true,
      "observe_sibling": true,
      "entropy_weight": 0.03,
      "entropy_gamma": 0.7,
      "ppo": false,
      "ppo_clip_ratio": 0.2,
      "ppo_n_iters": 10,
      "ppo_n_mb": 4,
      "pqt": false,
      "pqt_k": 10,
      "pqt_batch_size": 1,
      "pqt_weight": 200.0,
      "pqt_use_pg": false,
      "summary": false
   },
   "prior": {
      "relational": {
         "targets": [],
         "effectors": [],
         "relationship": null
      },
      "length": {
         "min_": 4,
         "max_": 30
      },
      "repeat": {
         "tokens": "const",
         "min_": null,
         "max_": 3
      },
      "inverse": {},
      "trig": {},
      "const": {},
      "no_inputs": {},
      "uniform_arity": {},
      "soft_length": {
         "loc": 10,
         "scale": 5
      },
      "language_model": {
         "weight": null
      }
   },
   "postprocess": {
      "show_count": 5,
      "save_plots": true
   }
}
```

**Comment by brendenpetersen** [comment] 2021-08-20 13:58
Hi @Sean-Reilly , thanks for the config! I am able to reproduce the bug. Looks like an issue when using `n_cores_batch > 1` and the `const` token. I can reproduce the bug with a simplified config:

```
{
"task" : {
    "function_set" : ["add", "mul", "div", "sub", "const"]
},
"training" : {
        "n_samples" : 100,
        "batch_size" : 10,
        "n_cores_batch" : 2
    }
}
```

I will look into this and report back! Thanks.

**Comment by brendenpetersen** [comment] 2021-08-20 14:27
Hi @Sean-Reilly, as a temporary hack, you can add `pool = None` in `train.py` at the beginning of the `learn()` function. That will break some other use cases (namely, the `control` task when using PyBullet envs), but should be just fine for `regression`.

A real fix will be incoming.

**Comment by brendenpetersen** [comment] 2021-12-16 17:01
This should be fixed in the newest release.

**Closed by brendenpetersen** 2021-12-16 17:01 UTC
